---
  
- name: Launch EC2 instance
  hosts: localhost

  tasks:
    - name: Launch EC2 instance
      ec2:
        region: us-east-1
        key_name: cloud
        instance_type: t2.micro
        image: ami-07d9b9ddc6cd8dd30
        count: 1
        instance_tags:
          Name: gvn
...
